apiVersion: api.assignment.io/v1
kind: ClusterScan
metadata:
  # labels:
  #   app.kubernetes.io/name: clusterscan
  #   app.kubernetes.io/instance: clusterscan-sample
  #   app.kubernetes.io/part-of: homeassignment
  #   app.kubernetes.io/managed-by: kustomize
  #   app.kubernetes.io/created-by: homeassignment
  name: clusterscan-sample
spec:
  type: "foo"
  setting: "default"
  # TODO(user): Add fields here
